/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crudsenzadb;

import crudsenzadb.event.AddEvent;
import crudsenzadb.event.AnnullaEvent;
import crudsenzadb.event.ConfermaEvent;
import crudsenzadb.event.ModificaEvent;
import crudsenzadb.event.RicercaEvent;
import crudsenzadb.event.RimuoviEvent;
import crudsenzadb.state.Automa;

/**
 *
 * @author lenovo
 */
public class CrudSenzaDbUI extends javax.swing.JFrame implements UIAutomabile {

    private Automa automa;

    /**
     * Creates new form CrudSenzaDbUI
     */
    public CrudSenzaDbUI() {
        initComponents();
        automa = new Automa(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CodiceText = new javax.swing.JTextField();
        DescrizioneText = new javax.swing.JTextField();
        ModificaButton = new javax.swing.JButton();
        ConfermaButton = new javax.swing.JButton();
        AnnullaButton = new javax.swing.JButton();
        RimuoviButton = new javax.swing.JButton();
        NuovaButton = new javax.swing.JButton();
        CercaText = new javax.swing.JTextField();
        CercaButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CodiceText.setText("Codice");
        CodiceText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodiceTextActionPerformed(evt);
            }
        });

        DescrizioneText.setText("Descrizione");
        DescrizioneText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescrizioneTextActionPerformed(evt);
            }
        });

        ModificaButton.setText("Modifica");
        ModificaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificaButtonActionPerformed(evt);
            }
        });

        ConfermaButton.setText("Conferma");
        ConfermaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfermaButtonActionPerformed(evt);
            }
        });

        AnnullaButton.setText("Annulla");
        AnnullaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnullaButtonActionPerformed(evt);
            }
        });

        RimuoviButton.setText("Rimuovi");
        RimuoviButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RimuoviButtonActionPerformed(evt);
            }
        });

        NuovaButton.setText("Nuova");
        NuovaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuovaButtonActionPerformed(evt);
            }
        });

        CercaText.setText("Cerca");

        CercaButton.setText("Cerca");
        CercaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CercaButtonActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ModificaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ConfermaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AnnullaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RimuoviButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CercaText, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CercaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CodiceText, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(DescrizioneText, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NuovaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(116, 116, 116))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CodiceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DescrizioneText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(NuovaButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ModificaButton)
                    .addComponent(ConfermaButton)
                    .addComponent(AnnullaButton)
                    .addComponent(RimuoviButton))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CercaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CercaButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CodiceTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodiceTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodiceTextActionPerformed

    private void DescrizioneTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescrizioneTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescrizioneTextActionPerformed

    private void ModificaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificaButtonActionPerformed
        automa.next(new ModificaEvent());
    }//GEN-LAST:event_ModificaButtonActionPerformed

    private void RimuoviButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RimuoviButtonActionPerformed
        automa.next(new RimuoviEvent());
    }//GEN-LAST:event_RimuoviButtonActionPerformed

    private void AnnullaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnullaButtonActionPerformed
       automa.next(new AnnullaEvent());
    }//GEN-LAST:event_AnnullaButtonActionPerformed

    private void ConfermaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfermaButtonActionPerformed
        automa.next(new ConfermaEvent(true));
    }//GEN-LAST:event_ConfermaButtonActionPerformed

    private void CercaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CercaButtonActionPerformed
        automa.next(new RicercaEvent());
    }//GEN-LAST:event_CercaButtonActionPerformed

    private void NuovaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuovaButtonActionPerformed
        automa.next(new AddEvent());
    }//GEN-LAST:event_NuovaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrudSenzaDbUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrudSenzaDbUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrudSenzaDbUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrudSenzaDbUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrudSenzaDbUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnnullaButton;
    private javax.swing.JButton CercaButton;
    private javax.swing.JTextField CercaText;
    private javax.swing.JTextField CodiceText;
    private javax.swing.JButton ConfermaButton;
    private javax.swing.JTextField DescrizioneText;
    private javax.swing.JButton ModificaButton;
    private javax.swing.JButton NuovaButton;
    private javax.swing.JButton RimuoviButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void vaiStatoAggiungi() {
        CodiceText.setVisible(true);
        DescrizioneText.setVisible(true);
        CercaText.setVisible(false);
        ModificaButton.setVisible(false);
        RimuoviButton.setVisible(false);
        AnnullaButton.setVisible(true);
        ConfermaButton.setVisible(true);
        NuovaButton.setVisible(false);
        CercaButton.setVisible(false);
        jTable1.setVisible(false);
    }

    @Override
    public void vaiStatoModifica() {
        CodiceText.setVisible(true);
        DescrizioneText.setVisible(true);
        CercaText.setVisible(false);
        ModificaButton.setVisible(false);
        RimuoviButton.setVisible(false);
        AnnullaButton.setVisible(true);
        ConfermaButton.setVisible(true);
        NuovaButton.setVisible(false);
        CercaButton.setVisible(false);
        jTable1.setVisible(false);
    }

    @Override
    public void vaiStatoRicerca() {
        CodiceText.setVisible(false);
        DescrizioneText.setVisible(false);
        CercaText.setVisible(true);
        ModificaButton.setVisible(false);
        RimuoviButton.setVisible(false);
        AnnullaButton.setVisible(false);
        ConfermaButton.setVisible(false);
        NuovaButton.setVisible(true);
        CercaButton.setVisible(true);
        jTable1.setVisible(true);
    }

    @Override
    public void vaiStatoRimuovi() {
        CodiceText.setVisible(true);
        DescrizioneText.setVisible(true);
        CercaText.setVisible(false);
        ModificaButton.setVisible(false);
        RimuoviButton.setVisible(false);
        AnnullaButton.setVisible(true);
        ConfermaButton.setVisible(true);
        NuovaButton.setVisible(false);
        CercaButton.setVisible(false);
        jTable1.setVisible(false);
    }

    @Override
    public void vaiStatoVisualizza() {
        CodiceText.setVisible(false);
        DescrizioneText.setVisible(false);
        CercaText.setVisible(true);
        ModificaButton.setVisible(true);
        RimuoviButton.setVisible(true);
        AnnullaButton.setVisible(false);
        ConfermaButton.setVisible(false);
        NuovaButton.setVisible(true);
        CercaButton.setVisible(true);
        jTable1.setVisible(true);
    }
}
